/*
  Sketch generated by the Arduino IoT Cloud Thing "Team 9"
  https://create.arduino.cc/cloud/things/070f064f-e1fc-43fb-adef-a276b3c93617

  Arduino IoT Cloud Variables description

  float rot_yaw;
  bool p13_LED;
*/

#include "thingProperties.h"
#include <math.h>

/* =========================
   FSR CONFIGURATION
   ========================= */

// --- ADC ---
const int ADC_PIN = A0;

// MKR WiFi 1010 is a 3.3V board
const float VCC     = 3.3;
const int   ADC_MAX = 4095;     // 12-bit ADC
const float R_FIXED = 10000.0;  // 10kΩ resistor

// --- Calibration (PLACEHOLDERS, FIX LATER) ---
const float A = 1.0e6;
const float B = -1.0;

// --- Filtering ---
const float ALPHA = 0.2;
float forceFiltN = 0.0;

/* =========================
   SETUP
   ========================= */
void setup() {
  Serial.begin(115200);
  delay(1500);

  // Cloud properties
  initProperties();

  // Cloud connection
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  // ADC config
  analogReadResolution(12);

  // Debug
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

/* =========================
   HELPER FUNCTIONS
   ========================= */

float adcToVoltage(int adc) {
  return (VCC * adc) / ADC_MAX;
}

float voltageToRfsr(float vout) {
  if (vout <= 0.001) return 1e9;
  if (vout >= VCC - 0.001) return 1.0;

  // Vcc -- FSR -- ADC -- R_FIXED -- GND
  return R_FIXED * (VCC / vout - 1.0);
}

float rfsrToForceN(float rfsr) {
  if (rfsr <= 0) return 0.0;

  float f = A * pow(rfsr, B);

  if (f < 0) f = 0;
  if (f > 5000) f = 5000;

  return f;
}

/* =========================
   LOOP
   ========================= */
void loop() {
  ArduinoCloud.update();

  int adc = analogRead(ADC_PIN);
  float vout = adcToVoltage(adc);
  float rfsr = voltageToRfsr(vout);
  float forceN = rfsrToForceN(rfsr);

  forceFiltN = (ALPHA * forceN) + ((1.0 - ALPHA) * forceFiltN);

  // =========================
  // CLOUD VARIABLE UPDATES
  // =========================
  fsr_raw_adc = adc;
  fsr_force_n = forceFiltN;

  if (adc < 10) {
    fsr_status = "NO CONTACT";
  } else if (adc > 4080) {
    fsr_status = "OVERLOAD";
  } else {
    fsr_status = "OK";
  }

  // Debug output
  Serial.print("ADC=");
  Serial.print(adc);
  Serial.print(" Vout=");
  Serial.print(vout, 4);
  Serial.print("V Rfsr=");
  Serial.print(rfsr, 1);
  Serial.print("Ω Force=");
  Serial.print(forceN, 2);
  Serial.print("N Filt=");
  Serial.print(forceFiltN, 2);
  Serial.println("N");

  delay(20);
}
